# Workflow for generating design docs

name: Generate Design Docs

on:
  push:
    branches:
      - Dev
      - Production
      - theron-dev
  workflow_dispatch:
    
jobs:
  srcDocs:
    runs-on: ubuntu-latest
    steps:
    - name: JSDoc Action
      run: ./src ./utils -r -d out
