# Workflow for generating design docs

name: Generate Design Docs

on:
  push:
    branches:
      - Dev
      - Production
  workflow_dispatch:
    
jobs:
  srcDocs:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src
        recurse: true
        output_dir: ./out/src
  utilsDocs:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./utils
        recurse: true
        output_dir: ./out/utils
    
