# Workflow for generating design docs

name: Generate Design Docs

on:
  push:
    branches:
      - Dev
      - Production
      - theron-dev
  workflow_dispatch:
    
jobs:
  srcDocs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: purrfectpets
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out/src
      - name: Push docs to repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "34664651+theronhalsey@users.noreply.github.com"
          git add ./out
          git commit -m "Updating Jsdoc documentation" || echo "No changes to commit"
          git push
